### ISSUE TITLE
Amazon Pay で都道府県が取得できないケースがある

### ISSUE THREAD

**Issue by nanasess** [nanasess/ec-cube2-amazonpay-v2#39]
```
2023/08/16 12:05:41 [/mypage/login.php] Fatal error(E_ERROR): Uncaught TypeError: Argument 1 passed to SC_Helper_AmazonPay::convertToPrefId() must be of the type string, null given, called in /var/www/html/aka-bane.com/data/vendor/nanasess/ec-cube2-amazonpay-v2/lib/data/class/helper/SC_Helper_AmazonPay.php on line 396 and defined in /var/www/html/aka-bane.com/data/vendor/nanasess/ec-cube2-amazonpay-v2/lib/data/class/helper/SC_Helper_AmazonPay.php:209
Stack trace:
#0 /var/www/html/aka-bane.com/data/vendor/nanasess/ec-cube2-amazonpay-v2/lib/data/class/helper/SC_Helper_AmazonPay.php(396): SC_Helper_AmazonPay::convertToPrefId()
#1 /var/www/html/aka-bane.com/data/class/pages/mypage/LC_Page_AbstractMypage.php(113): SC_Helper_AmazonPay->registerCustomer()
#2 /var/www/html/aka-bane.com/data/class/pages/mypage/LC_Page_Mypage_Login.php(52): LC_Page_AbstractMypage->process()
#3 /var/www/html/aka-bane.com/html/mypage/login.php(28): LC_Page_Mypage_Login->process()
#4 {main}
  thrown on [/var/www/html/aka-bane.com/data/vendor/nanasess/ec-cube2-amazonpay-v2/lib/data/class/helper/SC_Helper_AmazonPay.php(209)] from 150.9.155.70
customer_id =
```

**Comment by nanasess** [comment]
`Aichi-ken` と入力されているケースがある
